version: '3'

networks:
  laravel:

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    restart: always
    volumes:
      - .:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - ${DOCKER_NGINX_PORT}:80
    depends_on:
      - app
    networks:
      - laravel

  app:
    user: "1000:1000"
    container_name: ${PROJECT_NAME}_app
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:8.0
    restart: always
    volumes:
      - /home/mysql/${PROJECT_NAME}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_USER: ${DOCKER_DB_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    ports:
      - 3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    networks:
      - laravel

  npm:
    image: node:18
    container_name: npm
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: [ "npm" ]
    entrypoint: [ "npm" ]
    networks:
      - laravel

